### ISSUE TITLE
The MD5 generated by boost-uuid-1.70.0 and boost-uuid-1.71.0 are different

### ISSUE THREAD

**Issue by whu-ysw** [boostorg/uuid#111]
MD5(1) = C4CA4238A0B923820DCC509A6F75849B based on boost-uuid-1.70.0
while
MD5(1) = 3842CAC48223B9A09A50CC0D9B84756F based on boost-uuid-1.71.0
(https://wandbox.org/permlink/CJ0MMunEhYCRe6Cd)

The 1.70.0 version is right verified by other HASH tools. How to correct it if I want to keep using the version 1.71,0. Thanks in advance.

**Comment by Lastique** [comment]
Likely caused by https://github.com/boostorg/uuid/pull/109, see [Release Notes](https://www.boost.org/users/history/version_1_71_0.html) for Boost.UUID in 1.71.

Boost.UUID does not provide a public component for MD5 generation. What you're using is an implementation detail of a name generator, it does not have to give a compliant MD5, as other tools do.

**Comment by whu-ysw** [comment]
Oh! Thank you very much!! I realise how I was careless when I read the note.
